version: '3'
services:
  user:
    container_name: user-microservice
    image: node:16-alpine
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    ports:
      - 50051:50051
    environment:
      - NODE_ENV=development
    command: npm run start:dev

  grpc-test:
   image: gusaul/grpcox:latest
   ports:
     - 6969:6969